"""estrutura inicial

Revision ID: 791f381cee80
Revises: 
Create Date: 2026-08-15 21:08:58.683918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '791f381cee80'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuracoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_instituicao', sa.String(length=200), nullable=False),
    sa.Column('direcao', sa.String(length=200), nullable=False),
    sa.Column('morada', sa.String(length=255), nullable=True),
    sa.Column('contacto', sa.String(length=80), nullable=True),
    sa.Column('email_contacto', sa.String(length=150), nullable=True),
    sa.Column('rodape_pdf', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('perfil', sa.String(length=30), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('notas_saida',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_referencia', sa.String(length=50), nullable=False),
    sa.Column('data_emissao', sa.Date(), nullable=False),
    sa.Column('funcionario', sa.String(length=150), nullable=False),
    sa.Column('email_funcionario', sa.String(length=150), nullable=False),
    sa.Column('departamento', sa.String(length=120), nullable=False),
    sa.Column('motivo', sa.String(length=200), nullable=False),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(length=30), nullable=False),
    sa.Column('criado_por', sa.Integer(), nullable=False),
    sa.Column('aprovado_por', sa.Integer(), nullable=True),
    sa.Column('data_aprovacao', sa.DateTime(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.Column('data_conclusao', sa.DateTime(), nullable=True),
    sa.Column('pdf_path', sa.String(length=255), nullable=True),
    sa.Column('comentario_decisao', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['aprovado_por'], ['users.id'], ),
    sa.ForeignKeyConstraint(['criado_por'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notas_saida', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notas_saida_email_funcionario'), ['email_funcionario'], unique=False)
        batch_op.create_index(batch_op.f('ix_notas_saida_estado'), ['estado'], unique=False)
        batch_op.create_index(batch_op.f('ix_notas_saida_funcionario'), ['funcionario'], unique=False)
        batch_op.create_index(batch_op.f('ix_notas_saida_numero_referencia'), ['numero_referencia'], unique=True)

    op.create_table('historico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nota_id', sa.Integer(), nullable=False),
    sa.Column('utilizador', sa.String(length=150), nullable=False),
    sa.Column('acao', sa.String(length=255), nullable=False),
    sa.Column('data_hora', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['nota_id'], ['notas_saida.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('historico', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_historico_data_hora'), ['data_hora'], unique=False)

    op.create_table('itens_nota',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nota_id', sa.Integer(), nullable=False),
    sa.Column('tipo_item', sa.String(length=80), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=False),
    sa.Column('numero_serie', sa.String(length=100), nullable=True),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['nota_id'], ['notas_saida.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('itens_nota')
    with op.batch_alter_table('historico', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_historico_data_hora'))

    op.drop_table('historico')
    with op.batch_alter_table('notas_saida', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notas_saida_numero_referencia'))
        batch_op.drop_index(batch_op.f('ix_notas_saida_funcionario'))
        batch_op.drop_index(batch_op.f('ix_notas_saida_estado'))
        batch_op.drop_index(batch_op.f('ix_notas_saida_email_funcionario'))

    op.drop_table('notas_saida')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('configuracoes')
    # ### end Alembic commands ###
