"""campos do exemplar da nota de saida

Revision ID: ee7cc41d9379
Revises: 791f381cee80
Create Date: 2026-08-15 22:14:52.618914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee7cc41d9379'
down_revision = '791f381cee80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('configuracoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('origem_de', sa.String(length=80), server_default='Informática', nullable=False))
        batch_op.add_column(sa.Column('origem_local', sa.String(length=120), server_default='Sede IT', nullable=False))
        batch_op.add_column(sa.Column('local_emissao', sa.String(length=80), server_default='Maputo', nullable=False))

    with op.batch_alter_table('notas_saida', schema=None) as batch_op:
        batch_op.add_column(sa.Column('origem_local', sa.String(length=120), server_default='Sede IT', nullable=False))
        batch_op.add_column(sa.Column('local_emissao', sa.String(length=80), server_default='Maputo', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notas_saida', schema=None) as batch_op:
        batch_op.drop_column('local_emissao')
        batch_op.drop_column('origem_local')

    with op.batch_alter_table('configuracoes', schema=None) as batch_op:
        batch_op.drop_column('local_emissao')
        batch_op.drop_column('origem_local')
        batch_op.drop_column('origem_de')

    # ### end Alembic commands ###
