#Security props
config.security.salt=10
config.verifier.max-attempts=5
config.login.lock-time=10
config.encrypton.keys-size=1024
config.token.delimiter = &
config.jwt.secret=asdfSFS34wfsdfsdfSDSD32dfsddDDerQSNCK34SOWEK5354fdgdf4
config.jwt.validity=8
config.public-key=classpath:keys/public.pem
config.private-key=classpath:keys/private.pem

#SSL Config
server.ssl.key-store-type=PKCS12
server.ssl.key-store=classpath:keys/certificate.p12
server.ssl.key-store-password=hlichnon
server.ssl.key-alias=tomcat